version: "3.8"

services:
    app:
        image: app:latest
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        container_name: app
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            database:
                condition: service_healthy

    database:
        image: postgres:14.18-bookworm
        container_name: app_db
        ports:
            - 5434:5432
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
            interval: 10s
            timeout: 5s
            retries: 5

    nginx:
        image: nginx:stable-alpine
        container_name: app_nginx
        ports:
        - 8000:80
        volumes:
        - ./:/var/www
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
        - app

volumes:
    pgdata: ~