name: Build Laravel Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set Image Tag
        id: set-tag
        run: echo "tag=board-yet:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker compose build
          docker tag app board-yet:${{ github.sha }}
          docker save board-yet:${{ github.sha }} | gzip > image.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: image.tar.gz
