name: Deploy Board Yet to EC2

on:
  push:
    branches: 
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST }} << 'EOF'
            set -e

            cd ${{ secrets.DEPLOY_DIR }}

            if [ ! -d .git ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git pull origin main
            fi

            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d --build

            docker exec app php artisan migrate --force
            docker exec app php artisan config:cache
            docker exec app php artisan route:cache
            docker exec app php artisan view:cache
          EOF