name: Run PHPStan

on:
  workflow_run:
    workflows: ["Build Laravel Docker Image"]
    types:
      - completed

jobs:
  phpstan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: app-image

      - name: Load Docker Image
        run: gunzip -c image.tar.gz | docker load

      - name: Run PHPStan
        run: docker run --rm board-yet:${{ github.sha }} phpstan analyse app