name: Board Yet Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set Image Tag
        id: set-tag
        run: echo "tag=board-yet:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker compose build
          docker tag app board-yet:${{ github.sha }}
          docker save board-yet:${{ github.sha }} | gzip > image.tar.gz

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: image.tar.gz

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Built Image
        uses: actions/download-artifact@v4
        with:
          name: app-image

      - name: Load Docker Image
        run: |
          gunzip -c image.tar.gz | docker load

      - name: Run PHPStan
        run: docker run --rm board-yet:${{ github.sha }} phpstan analyse app

      - name: Run Laravel Migrations
        run: docker run --rm board-yet:${{ github.sha }} php artisan migrate --force

      - name: Run Laravel Tests
        run: docker run --rm board-yet:${{ github.sha }} php artisan test

      - name: Shutdown Docker Compose
        if: always()
        run: docker compose down

    