name: Board Yet Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: board_yet_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose up -d

      - name: Wait for services
        run: sleep 15

      - name: Run PHPStan
        run: docker compose exec app phpstan analyse app

      - name: Run PHPCS
        run: docker compose exec app phpcs --standard=phpcs.xml app

      - name: Run PHPMD
        run: docker compose exec app phpmd app text phpmd.xml

      - name: Run Laravel Migrations
        run: docker compose exec -T app php artisan migrate --force

      - name: Run Laravel Tests
        run: docker compose exec -T app php artisan test

      - name: Shutdown Docker Compose
        if: always()
        run: docker compose down

    