name: Run Laravel Tests

on:
  workflow_run:
    workflows: ["Build Laravel Docker Image"]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: board_yet
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: cp .env.testing .env

      - uses: actions/download-artifact@v4
        with:
          name: app-image

      - name: Load Docker Image
        run: gunzip -c image.tar.gz | docker load

      - name: Generate Laravel App Key
        run: docker run --rm -v $PWD:/var/www --network host board-yet:${{ github.sha }} php artisan key:generate

      - name: Run Migrations
        run: docker run --rm -v $PWD:/var/www --network host board-yet:${{ github.sha }} php artisan migrate --force

      - name: Run Laravel Tests
        run: docker run --rm -v $PWD:/var/www --network host board-yet:${{ github.sha }} php artisan test